export const TOUR_ADD_HIGHLIGHT = 'TOUR_ADD_HIGHLIGHT';
export const TOUR_REMOVE_HIGHLIGHT = 'TOUR_REMOVE_HIGHLIGHT';
export const TOUR_START_HIGHLIGHT = 'TOUR_START_HIGHLIGHT';
export const TOUR_STOP_HIGHLIGHT = 'TOUR_STOP_HIGHLIGHT';
export const TOUR_NEXT_HIGHLIGHT = 'TOUR_NEXT_HIGHLIGHT';
export const TOUR_PREV_HIGHLIGHT = 'TOUR_PREV_HIGHLIGHT';
export const TOUR_START_HIGHLIGHT_TIMER = 'TOUR_START_HIGHLIGHT_TIMER';
export const TOUR_FLUSH_HIGHLIGHT = 'TOUR_FLUSH_HIGHLIGHT';
