export const translations = {
  'rbf.page.footer.followUs' : 'Suivez-nous',
  'rbf.page.header.menuIcon' : 'Menu',
  'rbf.button.help.help': 'Afficher les aides',
  'rbf.trello.card.addLink.help': 'Nouvelle carte',
  'rbf.trello.card.addLink': 'Nouvelle carte',
  'rbf.trello.card.update': 'Modifier la carte',
  'rbf.trello.card.remove': 'Détacher la carte',
  'rbf.trello.card.delete': 'Supprimer la carte',
  'rbf.trello.card.searchLink.help': 'Carte existante',
  'rbf.trello.card.searchLink': 'Carte existante',
  'rbf.trello.card.search.num.placeholder': 'Numéro',
  'rbf.trello.card.form.title.placeholder': 'Titre',
  'rbf.trello.card.form.label.placeholder': 'Projet',
  'rbf.trello.card.form.description.placeholder': 'Description',
  'rbf.trello.card.form.add.help': 'Ajouter',
  'rbf.trello.card.form.add': 'Ajouter',
  'rbf.trello.card.form.cancel': 'Annuler',
  'rbf.trello.card.form.cancel.help': 'Annuler',
  'rbf.trello.lane.form.title.placeholder': 'Titre',
  'rbf.trello.lane.form.add.help': 'Ajouter',
  'rbf.trello.lane.form.add': 'Ajouter',
  'rbf.trello.lane.form.cancel': 'Annuler',
  'rbf.trello.lane.title.placeholder': 'Titre de la colonne',
  'rbf.trello.lane.delete': 'Supprimer la colonne',
  'rbf.trello.lane.add': 'Nouvelle colonne',
  'rbf.list.more': 'Plus',
  'rbf.list.title.sort.up': 'Tri croissant',
  'rbf.list.title.sort.down': 'Tri décroissant',
  'rbf.list.title.sort.none': 'Aucun tri',
  'rbf.list.header.sort.help': 'Liste des colonnes utilisées pour le tri en cours [RC](+) : croissant [RC](-) : décroissant',
  'rbf.list.header.search.help': 'Recherche rapide sur les champs indiqués, en recherche de type contient',
  'rbf.list.header.filter.help': 'Ouvrir le panneau de gestion[RC]des filtres et tris',
  'rbf.list.header.filter.setDefaultFilter': 'Activer les filtres par défaut',
  'rbf.list.header.filter.removeDefaultFilter': 'Supprimer les filtres par défaut',
  'rbf.list.header.filter.removeCustomFilter': 'Supprimer les filtres ajoutés aux filtres par défaut',
  'rbf.list.header.filter.removeAllFilter': 'Supprimer les filtres',
};
